postgres:
    image: postgres:latest
    restart: always
    ports:
        - "5432:5432"
    environment:
        - POSTGRES_USER=airflow
        - POSTGRES_PASSWORD=airflow

rabbitmq:
    image: rabbitmq:management
    restart: always
    ports:
        - "15672:15672"
        - "5672:5672"
    environment:
        - RABBITMQ_DEFAULT_USER=airflow
        - RABBITMQ_DEFAULT_PASS=airflow
        - RABBITMQ_DEFAULT_VHOST=airflow

webserver:
    image: voyagerdata/airflow
    restart: always
    volumes:
         - .:/usr/local/airflow
    environment:
        - AIRFLOW_HOME=/usr/local/airflow
    ports:
        - "8080:8080"
    links:
        - postgres:postgres
        - rabbitmq:rabbitmq
        - worker:worker
        - scheduler:scheduler
    command: webserver

flower:
    image: voyagerdata/airflow
    restart: always
    environment:
        - AIRFLOW_HOME=/usr/local/airflow
    ports:
        - "5555:5555"
    links:
        - rabbitmq:rabbitmq
    command: flower

scheduler:
    image: voyagerdata/airflow
    restart: always
    volumes:
        - .:/usr/local/airflow
    environment:
        - AIRFLOW_HOME=/usr/local/airflow
    links:
        - postgres:postgres
        - rabbitmq:rabbitmq
    command: scheduler

worker:
    image: voyagerdata/airflow
    restart: always
    volumes:
        - .:/usr/local/airflow
    environment:
        - AIRFLOW_HOME=/usr/local/airflow
    ports:
        - "8793:8793"
    links:
        - postgres:postgres
        - rabbitmq:rabbitmq
    command: worker
